### ISSUE TITLE
Magento 2.3 not compatible

### ISSUE THREAD

**Issue by nishantgupta1287** [razorpay/razorpay-magento#123]
php7.2 /usr/local/bin/composer require razorpay/magento

Using version ^2.6 for razorpay/magento
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/framework 101.0.7 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.16 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 101.0.6 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.15 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.14 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 101.0.5 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 101.0.4 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.13 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 101.0.3 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.12 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.20 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 101.0.2 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.11 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.10 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 101.0.1 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.19 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 101.0.0 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.18 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.9 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.8 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.17 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.16 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.7 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.6 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.15 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.5 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.14 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.4 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.13 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.3 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.2 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.12 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.1 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.11 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.10 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.1.0 requires php ~5.6.0|7.0.2|~7.0.6 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.9 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.8 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.7 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.6 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.5 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.4 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.3 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - magento/framework 100.0.2 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.14) does not satisfy that requirement.
    - razorpay/magento 2.6.0 requires magento/framework ~100.0||~101.0 -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.1.0, 100.0.10, 100.0.11, 100.1.1, 100.0.12, 100.1.2, 100.1.3, 100.0.13, 100.1.4, 100.0.14, 100.1.5, 100.0.15, 100.1.6, 100.1.7, 100.0.16, 100.0.17, 100.1.8, 100.1.9, 100.0.18, 101.0.0, 100.0.19, 101.0.1, 100.1.10, 100.1.11, 101.0.2, 100.0.20, 100.1.12, 101.0.3, 100.1.13, 101.0.4, 101.0.5, 100.1.14, 100.1.15, 101.0.6, 100.1.16, 101.0.7].
    - Installation request for razorpay/magento ^2.6 -> satisfiable by razorpay/magento[2.6.0].

**Comment by nishantgupta1287** [comment]
Please resolve the issue or let me know the steps to resolve it.

**Comment by knambiar** [comment]
Could we get an update on this issue?

**Comment by knambiar** [comment]
FYI I spoke to razorpay support and they said it should be available by mid-April

**Comment by iambaljitdhanoa** [comment]
We have fixed razorpay issue in magento 2.3

**Comment by knambiar** [comment]
> We have fixed razorpay issue in magento 2.3

Hi, where can I see this code?

**Comment by iambaljitdhanoa** [comment]
we have changes some files on the local server after that its working fine you can easily do it

**Comment by nishantgupta1287** [comment]
I am still getting same error while installing it from Composer. Please share the Updated code.

**Comment by nishantgupta1287** [comment]
@seherkdc


composer require razorpay/magento
Using version ^2.6 for razorpay/magento
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/framework 101.0.7 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.15) does not satisfy that requirement.
    - magento/framework 100.1.16 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.15) does not satisfy that requirement.
    - magento/framework 101.0.6 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.15) does not satisfy that requirement.
    - magento/framework 100.1.15 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.15) does not satisfy that requirement.
    - magento/framework 100.1.14 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.15) does not satisfy that requirement.
    - magento/framework 101.0.5 requires php ~7.0.13|~7.1.0 -> your PHP version (7.2.15) does not satisfy that requirement.
    - magento/framework 101.0.4 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.15) does not satisfy that requirement.
    - magento/framework 100.1.13 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.15) does not satisfy that requirement.
    - magento/framework 101.0.3 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.15) does not satisfy that requirement.
    - magento/framework 100.1.12 requires php ~5.6.5|7.0.2|7.0.4|~7.0.6 -> your PHP version (7.2.15) does not satisfy that requirement.

**Comment by iambaljitdhanoa** [comment]
Hello

You can easily do it we have already done it Magento 2.3

<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=9baa77ad-dcd9-4b6f-b2c5-99d5486baf9e>
I’m
protected online with Avast Free Antivirus. Get it here — it’s free forever.
<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=9baa77ad-dcd9-4b6f-b2c5-99d5486baf9e>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by harman28** [comment]
Support for Magento 2.3 was added in [v.2.6.1](https://github.com/razorpay/razorpay-magento/releases/tag/2.6.1).
